export const REQUEST_RESOLVER = 'REQUEST_RESOLVER';
export const RECEIVE_RESOLVER = 'RECEIVE_RESOLVER';

export const REQUEST_SET_RESOLVER = 'REQUEST_SET_RESOLVER';
export const WAITING_SET_RESOLVER = 'WAITING_SET_RESOLVER';
export const RECEIVE_SET_RESOLVER = 'RECEIVE_SET_RESOLVER';
export const ERROR_SET_RESOLVER = 'ERROR_SET_RESOLVER';

export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';

export const MULTICHAIN_RESOLVER = 'MULTICHAIN_RESOLVER';
export const PUBLIC_RESOLVER = 'PUBLIC_RESOLVER';
export const STRING_RESOLVER = 'STRING_RESOLVER';
export const UNKNOWN_RESOLVER = 'UNKNOWN_RESOLVER';
